///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Pagination {
/*
{
  "page": "1",
  "size": "10"
} 
*/

  String? page;
  String? size;

  Pagination({
    this.page,
    this.size,
  });
  Pagination.fromJson(Map<String, dynamic> json) {
    page = json['page']?.toString();
    size = json['size']?.toString();
  }

  Map<String, String> toJson() {
    final data = <String, String>{};
    if (page != null) data['page'] = page!;
    if (size != null) data['size'] = size!;
    return data;
  }
}
