///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SuccessMutation {
/*
{
  "success": false
} 
*/

  bool? success;

  SuccessMutation({
    this.success,
  });
  SuccessMutation.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}
