///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserProofileResponseUsersFiles {
/*
{
  "fileId": "0a37e788-f52d-41d8-9948-b0610cf5d8b3",
  "fileName": "file/1736051199737-400616301.jpg",
  "fileSize": "870275",
  "type": "image/jpeg",
  "createdAt": "2025-01-04T05:41:29.722Z",
  "updatedAt": "2025-01-05T04:26:39.777Z",
  "toDoId": "0a37e788-f52d-41d8-9948-b0610cf5d8b3",
  "userId": "1c250a77-8bbc-49b6-b4e5-a61b53300997"
} 
*/

  String? fileId;
  String? fileName;
  String? fileSize;
  String? type;
  String? createdAt;
  String? updatedAt;
  String? toDoId;
  String? userId;

  UserProofileResponseUsersFiles({
    this.fileId,
    this.fileName,
    this.fileSize,
    this.type,
    this.createdAt,
    this.updatedAt,
    this.toDoId,
    this.userId,
  });
  UserProofileResponseUsersFiles.fromJson(Map<String, dynamic> json) {
    fileId = json['fileId']?.toString();
    fileName = json['fileName']?.toString();
    fileSize = json['fileSize']?.toString();
    type = json['type']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    toDoId = json['toDoId']?.toString();
    userId = json['userId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['fileId'] = fileId;
    data['fileName'] = fileName;
    data['fileSize'] = fileSize;
    data['type'] = type;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['toDoId'] = toDoId;
    data['userId'] = userId;
    return data;
  }
}

class UserProofileResponseUsers {
/*
{
  "userId": "1c250a77-8bbc-49b6-b4e5-a61b53300997",
  "firstName": "Girish",
  "lastName": "Parate",
  "password": "$2b$08$ihfZCp0o8swv9KlZTbZBU.q8FtV7d5J9hFiY1qDapvBFWBoWa7KpO",
  "email": "parategirish50@gmail.com",
  "createdAt": "2024-12-21T02:23:26.192Z",
  "updatedAt": "2025-01-05T02:37:09.196Z",
  "deletedAt": "2025-01-05T02:37:09.196Z",
  "files": [
    {
      "fileId": "0a37e788-f52d-41d8-9948-b0610cf5d8b3",
      "fileName": "file/1736051199737-400616301.jpg",
      "fileSize": "870275",
      "type": "image/jpeg",
      "createdAt": "2025-01-04T05:41:29.722Z",
      "updatedAt": "2025-01-05T04:26:39.777Z",
      "toDoId": "0a37e788-f52d-41d8-9948-b0610cf5d8b3",
      "userId": "1c250a77-8bbc-49b6-b4e5-a61b53300997"
    }
  ]
} 
*/

  String? userId;
  String? firstName;
  String? lastName;
  String? password;
  String? email;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  List<UserProofileResponseUsersFiles?>? files;

  UserProofileResponseUsers({
    this.userId,
    this.firstName,
    this.lastName,
    this.password,
    this.email,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.files,
  });
  UserProofileResponseUsers.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    firstName = json['firstName']?.toString();
    lastName = json['lastName']?.toString();
    password = json['password']?.toString();
    email = json['email']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    deletedAt = json['deletedAt']?.toString();
    if (json['files'] != null) {
      final v = json['files'];
      final arr0 = <UserProofileResponseUsersFiles>[];
      v.forEach((v) {
        arr0.add(UserProofileResponseUsersFiles.fromJson(v));
      });
      files = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['password'] = password;
    data['email'] = email;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['deletedAt'] = deletedAt;
    if (files != null) {
      final v = files;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['files'] = arr0;
    }
    return data;
  }
}

class UserProofileResponse {
/*
{
  "users": {
    "userId": "1c250a77-8bbc-49b6-b4e5-a61b53300997",
    "firstName": "Girish",
    "lastName": "Parate",
    "password": "$2b$08$ihfZCp0o8swv9KlZTbZBU.q8FtV7d5J9hFiY1qDapvBFWBoWa7KpO",
    "email": "parategirish50@gmail.com",
    "createdAt": "2024-12-21T02:23:26.192Z",
    "updatedAt": "2025-01-05T02:37:09.196Z",
    "deletedAt": "2025-01-05T02:37:09.196Z",
    "files": [
      {
        "fileId": "0a37e788-f52d-41d8-9948-b0610cf5d8b3",
        "fileName": "file/1736051199737-400616301.jpg",
        "fileSize": "870275",
        "type": "image/jpeg",
        "createdAt": "2025-01-04T05:41:29.722Z",
        "updatedAt": "2025-01-05T04:26:39.777Z",
        "toDoId": "0a37e788-f52d-41d8-9948-b0610cf5d8b3",
        "userId": "1c250a77-8bbc-49b6-b4e5-a61b53300997"
      }
    ]
  }
} 
*/

  UserProofileResponseUsers? users;

  UserProofileResponse({
    this.users,
  });
  UserProofileResponse.fromJson(Map<String, dynamic> json) {
    users = (json['users'] != null)
        ? UserProofileResponseUsers.fromJson(json['users'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (users != null) {
      data['users'] = users!.toJson();
    }
    return data;
  }
}
