///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginSuccessUser {
/*
{
  "userId": "d75720e8-b832-4170-97b2-5e8380c82493",
  "firstName": "Girish",
  "lastName": "parate",
  "email": "parategirish500@gmail.com",
  "createdAt": "2024-12-28T05:13:35.196Z",
  "updatedAt": "2025-01-04T11:16:26.762Z",
  "deletedAt": "2025-01-04T11:16:26.762Z"
} 
*/

  String? userId;
  String? firstName;
  String? lastName;
  String? email;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  LoginSuccessUser({
    this.userId,
    this.firstName,
    this.lastName,
    this.email,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  LoginSuccessUser.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    firstName = json['firstName']?.toString();
    lastName = json['lastName']?.toString();
    email = json['email']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    deletedAt = json['deletedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['email'] = email;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['deletedAt'] = deletedAt;
    return data;
  }
}

class LoginSuccess {
/*
{
  "user": {
    "userId": "d75720e8-b832-4170-97b2-5e8380c82493",
    "firstName": "Girish",
    "lastName": "parate",
    "email": "parategirish500@gmail.com",
    "createdAt": "2024-12-28T05:13:35.196Z",
    "updatedAt": "2025-01-04T11:16:26.762Z",
    "deletedAt": "2025-01-04T11:16:26.762Z"
  },
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJkNzU3MjBlOC1iODMyLTQxNzAtOTdiMi01ZTgzODBjODI0OTMiLCJpYXQiOjE3MzYwNjIxMzQsImV4cCI6MTczNjA2NTczNCwiaXNzIjoiZ2lyaXNoLmNvbSJ9.cq7N8wMK_OyMTF0mBRHMosSU2s4VMlT-CwK9EtcYzJo",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzYwNjIxMzQsImV4cCI6MTczNjA2NTczNCwiYXVkIjoiZDc1NzIwZTgtYjgzMi00MTcwLTk3YjItNWU4MzgwYzgyNDkzIiwiaXNzIjoiZ2lyaXNoLmNvbSJ9.APopiZ9cAroLMo8v4-dykD_Hg_zZ35bcLSLuebngR3c"
} 
*/

  LoginSuccessUser? user;
  String? accessToken;
  String? refreshToken;

  LoginSuccess({
    this.user,
    this.accessToken,
    this.refreshToken,
  });
  LoginSuccess.fromJson(Map<String, dynamic> json) {
    user =
        (json['user'] != null) ? LoginSuccessUser.fromJson(json['user']) : null;
    accessToken = json['accessToken']?.toString();
    refreshToken = json['refreshToken']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['accessToken'] = accessToken;
    data['refreshToken'] = refreshToken;
    return data;
  }
}
